app: spoke-fly
config:
  adminBackend:
    fromSecret: adminBackend
  texterBackend:
    fromSecret: texterBackend
  isMaintenanceMode:
    fromSecret: isMaintenanceMode
  adminTrafficRate:
    fromSecret: adminTrafficRate
